/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AppConfig {
  animeSelectWindowSize: AppConfigWindowSize;
  mainWindowSize: AppConfigWindowSize;
}

export interface AppConfigWindowSize {
  height: number;
  width: number;
}
